Packet Information
6.25, 222
end
Signals Information
0, SCG-Z, 3, 125, 20, signed
.graphable
..color: 0 0 250 255
.filter
..b: 1.0
..a: 1.0
..gain: 5
1, ECG, 3, 125, 18, signed
.graphable
..color: 250 0 0 255
.filter
..b: 1.0
..a: 1.0
..gain: 5
2, PPGG, 4, 31, 20, unsigned
.graphable
..color: 0 250 0 255
.filter
..b: 1.0
..a: 1.0
..gain: 5
3, num, 2, 6, 16, unsigned
4, TEMP, 2, 6, 16, signed
.digdisplay
..DecimalFormat: ##.##
..suffix: \u00B0C
5, SV, 4, 6, 32, signed
.digdisplay
..DecimalFormat: ###.#
..suffix: ml
6, SBP, 4, 6, 32, signed
.digdisplay
..DecimalFormat: ###.#
..suffix: mmHg
7, DBP, 4, 6, 32, signed
.digdisplay
..DecimalFormat: ###.#
..suffix: mmHg
8, HR, 4, 6, 32, float
.digdisplay
..DecimalFormat: ##.##
..suffix: bpm
9, rdet_last_r_idx, 4, 6, 32, signed
.digdisplay
..DecimalFormat: #
..suffix: smp
10, rdet_raw_idx, 4, 6, 32, signed
.digdisplay
..DecimalFormat: #
..suffix: smp
11, rdet_status, 1, 6, 8, unsigned
12, dbg_chunk_seq, 1, 6, 8, unsigned
13, dbg_r_abs, 4, 6, 32, signed
.digdisplay
..DecimalFormat: #
..suffix: smp
14, dbg_ecg_sample, 4, 75, 32, signed
end
Biometric Settings
end
Packet Structure
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
4
5
6
7
8
9
10
11
12
13
14
14
14
14
14
14
14
14
14
14
14
14
end
