Packet Information
25, 98
end
Signals Information
0, Packet, 2, 25, 16, unsigned
.digdisplay
1, EEG 1, 3, 100, 24, signed
.graphable
..color: 200 200 200 255
..graphHeight: 60
2, EEG 2, 3, 100, 24, signed
.graphable
..color: 200 200 200 255
..graphHeight: 60
3, EEG 3, 3, 100, 24, signed
.graphable
..color: 200 200 200 255
..graphHeight: 60
4, EEG 4, 3, 100, 24, signed
.graphable
..color: 200 200 200 255
..graphHeight: 60
5, EEG 5, 3, 100, 24, signed
.graphable
..color: 200 200 200 255
..graphHeight: 60
6, EEG 6, 3, 100, 24, signed
.graphable
..color: 200 200 200 255
..graphHeight: 60
7, Accel X, 2, 50, 16, signed
.graphable
..color: 250 0 0 255
..graphHeight: 50
8, Accel Y, 2, 50, 16, signed
.graphable
..color: 0 250 0 255
..graphHeight: 50
9, Accel Z, 2, 50, 16, signed
.graphable
..color: 0 0 250 255
..graphHeight: 50
10, Gyro X, 2, 50, 16, signed
.graphable
..color: 250 120 0 255
..graphHeight: 50
11, Gyro Y, 2, 50, 16, signed
.graphable
..color: 120 250 0 255
..graphHeight: 50
12, Gyro Z, 2, 50, 16, signed
.graphable
..color: 0 120 250 255
..graphHeight: 50
end
Biometric Settings
end
Packet Structure
0
1
1
1
1
2
2
2
2
3
3
3
3
4
4
4
4
5
5
5
5
6
6
6
6
7
8
9
10
11
12
7
8
9
10
11
12
end
RX Messages
end
TX Messages
end
